name = "self-destruct-message"
main = "src/index.ts"
compatibility_date = "2024-05-30"

[[kv_namespaces]]
binding = "MESSAGES"
id = "KV_NAMESPACE" # You will need to create a KV namespace and put its ID here